using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ItemManager : MonoBehaviour
{
    PhotonView pv;
    public enum ITEMTYPE
    {
        WOOD,      // 점첞
        STEEL,     // 칬첞
        DROPPEDTRACK,  // 찗써왆쵔 쮉챸 퀉익
        BUCKET,    // 졿쾖
        DYNAMITE,  // 큊콬
        AX,        // 옷씩
        PICK       // 썵쏡첇
    }
    public ITEMTYPE itemType;

    private void FixedUpdate()
    {
        if (pv != null && pv.IsMine)
        {
            PhotonTransformView transformView = GetComponent<PhotonTransformView>();
            if (transformView != null)
            {
                transformView.enabled = false;
            }
        }
        else
        {
            PhotonTransformView transformView = GetComponent<PhotonTransformView>();
            if (transformView != null)
            {
                transformView.enabled = true;
            }
        }
    }
}
